// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Data.Migrations
{
    [DbContext(typeof(EmailHandlerContext))]
    internal class EmailHandlerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Data.Models.EmailMessage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Body")
                    .HasColumnType("TEXT");

                b.Property<string>("Sender")
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<string>("Subject")
                    .HasColumnType("TEXT");

                b.Property<string>("ToRecipients")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("EmailMessages");
            });
#pragma warning restore 612, 618
        }
    }
}